name: 'Continuous Integrations'

on:
  push:
    branches: ['main']

jobs:
  lint:
    name: 'Run ESLint and Prettier'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout the repository'
        uses: 'actions/checkout@v3'

      - name: 'Setup Node.js and npm'
        uses: './.github/actions/setup'

      - name: 'Execute the lint script'
        run: 'npm run lint'


  test:
    name: 'Run unit tests with Jest'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout the repository'
        uses: 'actions/checkout@v3'

      - name: 'Setup Node.js and npm'
        uses: './.github/actions/setup'

      - name: 'Execute the test script'
        run: 'npm run test'

  bundle:
    name: 'Bundle package with Rollup.js'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout the repository'
        uses: 'actions/checkout@v3'

      - name: 'Setup Node.js and npm'
        uses: './.github/actions/setup'

      - name: 'Execute the build script'
        run: 'npm run build'

  npm-build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 16.x
          registry-url: ' https://registry.npmjs.org'
      - run: npm install
      - run: npm run build
        env:
          CI: true
      - name: npm version and publish
        uses: geemanjs/conventional-changelog-npm-publish@1.0.0
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
